Output particle heating XS in chi-tech format
ragusa/Njoy2ChiConverter pull request #2
Opened 2021-06-25 21:23 UTC by markNbaHoang12

Note: The "Remove the testing" commit is just me removing a few bookmarks for the parts that I add in the codes. It doesn't affect the functionality in anyway

2021-06-26 15:25 UTC, ragusa requested changes
several times in combiner, you are reverting to an old version of the file. do not do that. I will not be able to allow that merge request.

2021-06-26 15:25 UTC, ragusa commented on example2a.sh
> +--njoy_exec_name=njoy21 \
please leave njoy as in the orginal file

2021-06-26 15:25 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
> +    n_to_n_freegas_keys = ["free-gas"]
you are reverting to an old version of the file. do not do that. I will not be able to allow that merge request.

2021-06-26 15:25 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
> +    n_to_g_transfer_keys = ["(n,g)", "(n,inel)", "(n,np)",
you are reverting to an old version of the file. do not do that. I will not be able to allow that merge request.

2021-06-26 15:30 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
> +    n_to_g_transfer_keys = ["(n,g)", "(n,inel)", "(n,np)",
you are missing n_to_n_other_keys which is currently in my file. are you sure your branch is based on the latest version of my repo? you have have to do a pull from upstream (google this) to incorporate my changes. A fetch does get my changes in your local database but does not apply them. Maybe fetch from upstream + pull is what you need.

2021-06-26 15:31 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
> +                            "(n,t)", "(n,a)",
smae here

2021-06-26 15:31 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
>      # Adding all the neutron to gamma data
missing "# Adding all the other neutron to neutron data" and below

2021-06-26 15:31 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
>      for range_data in nranges_to_granges:
something is missing

2021-06-26 15:31 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
>      # Regular elastic scatter (MT-2)
missing

2021-06-26 15:31 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
missing

2021-06-26 15:32 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
missing

2021-06-26 15:32 UTC, ragusa commented on njoy_processor/Utils_Combiner.py
order of operations not the same. you have an old version

2021-06-26 15:33 UTC, ragusa requested changes
see if fetch + pull gets you my latest version of the file

2021-06-27 02:55 UTC, markNbaHoang12 commented
Dear Dr. Ragusa,

I'm sorry for the late reply. I looked into your comments on my pull
request and I've checked out if I could fetch+pull to get the latest
version of your repository. But it seems like from both the github website
and from the command line on the cluster, my version is currently up to
date with yours, apart from my addition that you weren't able to merge. I
attached the screenshot below for your reference, I've also tried to
manually compare the two Utils_Combiner, but they seem to be the same.
Should I reclone into the cluster and redo the pull request to make sure
everything is exactly the same ?

Mark Nguyen
[image: image.png]

Vào Th 7, 26 thg 6, 2021 vào lúc 10:33 Jean Ragusa <
***@***.***> đã viết:

> ***@***.**** requested changes on this pull request.
>
> see if fetch + pull gets you my latest version of the file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ragusa/Njoy2ChiConverter/pull/2#pullrequestreview-693317022>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUKZDCWIJLL4B2J5UW54CZDTUXXLRANCNFSM47KS2RTQ>
> .
>

2021-06-27 23:01 UTC, ragusa approved these changes

2021-06-27 23:01 UTC, merged